name: pp
description: "portfolio"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  firebase_storage: ^12.1.2
  http: ^1.2.2
  firebase_core: ^3.3.0
  firebase_storage_web: ^3.9.12
  url_launcher: ^6.3.0
  smooth_page_indicator: ^1.2.0+3
  another_flutter_splash_screen: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true
  generate: true
  assets:
    - images/
    - fonts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: fonts/NotoSansKR-Black.ttf
          weight: 900
        - asset: fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: fonts/NotoSansKR-Thin.ttf
          weight: 100
